name: Update IP List

on:
 # schedule:
  #  - cron: '0 */4 * * *' # 每3小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
        
    - name: Run script
      run: |
        [ -f CloudflareST ] || mkdir CloudflareST
        cd CloudflareST
        wget -N https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_amd64.tar.gz
        tar -zxf CloudflareST_linux_amd64.tar.gz
        rm CloudflareST_linux_amd64.tar.gz
        rm cfst_hosts.sh
        rm ip.txt
        rm ipv6.txt
        curl -o ip.txt https://ghproxy.cc/https://raw.githubusercontent.com/Sereinfy/best-ip/main/ip.txt
        chmod +x CloudflareST
        ./CloudflareST -allip -tp 443 -dn 20 -dt 8 -tll 40 -url https://cfspeed1.kkiyomi.top/300mb.bin
        
    - name: Commit and push changes
      run: |
        git config --global user.email "tianshideyou@proton.me"
        git config --global user.name "tianshipapa"
        if [ -n "$(git status --porcelain)" ]; then
          git add .

          git commit -m "Automatic update"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
